// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.16830
//    <NameSpace>com.matt</NameSpace><Collection>ObservableCollection</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>/sc</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings>System.Xml.Linq;System.IO</CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace com.matt {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml.Linq;
    using System.IO;
    using System.Collections.ObjectModel;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.16833")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="uri://matt.b/packet/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="uri://matt.b/packet/", IsNullable=false)]
    public partial class message : System.ComponentModel.INotifyPropertyChanged {
        
        private messageData dataField;
        
        private string senderField;
        
        private System.DateTime dateTimeField;
        
        private bool dateTimeFieldSpecified;
        
        private string typeField;
        
        public message() {
            this.dataField = new messageData();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public messageData data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField != null)) {
                    if ((dataField.Equals(value) != true)) {
                        this.dataField = value;
                        this.OnPropertyChanged("data");
                    }
                }
                else {
                    this.dataField = value;
                    this.OnPropertyChanged("data");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                if ((this.senderField != null)) {
                    if ((senderField.Equals(value) != true)) {
                        this.senderField = value;
                        this.OnPropertyChanged("sender");
                    }
                }
                else {
                    this.senderField = value;
                    this.OnPropertyChanged("sender");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                if ((dateTimeField.Equals(value) != true)) {
                    this.dateTimeField = value;
                    this.OnPropertyChanged("dateTime");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateTimeSpecified {
            get {
                return this.dateTimeFieldSpecified;
            }
            set {
                if ((dateTimeFieldSpecified.Equals(value) != true)) {
                    this.dateTimeFieldSpecified = value;
                    this.OnPropertyChanged("dateTimeSpecified");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField != null)) {
                    if ((typeField.Equals(value) != true)) {
                        this.typeField = value;
                        this.OnPropertyChanged("type");
                    }
                }
                else {
                    this.typeField = value;
                    this.OnPropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public virtual void OnPropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null)) {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.16833")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="uri://matt.b/packet/")]
    public partial class messageData : System.ComponentModel.INotifyPropertyChanged {
        
        private string textField;
        
        private byte[] binaryField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((this.textField != null)) {
                    if ((textField.Equals(value) != true)) {
                        this.textField = value;
                        this.OnPropertyChanged("text");
                    }
                }
                else {
                    this.textField = value;
                    this.OnPropertyChanged("text");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] binary {
            get {
                return this.binaryField;
            }
            set {
                if ((this.binaryField != null)) {
                    if ((binaryField.Equals(value) != true)) {
                        this.binaryField = value;
                        this.OnPropertyChanged("binary");
                    }
                }
                else {
                    this.binaryField = value;
                    this.OnPropertyChanged("binary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public virtual void OnPropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null)) {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.16833")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="uri://matt.b/packet/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="uri://matt.b/packet/", IsNullable=false)]
    public partial class packet : System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] dataField;
        
        private ObservableCollection<imagesTypeImage> imagesField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string osField;
        
        private string archField;
        
        private string uriField;
        
        private string versionField;
        
        private System.DateTime dateCreatedField;
        
        private bool dateCreatedFieldSpecified;
        
        private System.DateTime dateModifiedField;
        
        private bool dateModifiedFieldSpecified;
        
        public packet() {
            this.imagesField = new ObservableCollection<imagesTypeImage>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField != null)) {
                    if ((dataField.Equals(value) != true)) {
                        this.dataField = value;
                        this.OnPropertyChanged("data");
                    }
                }
                else {
                    this.dataField = value;
                    this.OnPropertyChanged("data");
                }
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("image")]
        public ObservableCollection<imagesTypeImage> images {
            get {
                return this.imagesField;
            }
            set {
                if ((this.imagesField != null)) {
                    if ((imagesField.Equals(value) != true)) {
                        this.imagesField = value;
                        this.OnPropertyChanged("images");
                    }
                }
                else {
                    this.imagesField = value;
                    this.OnPropertyChanged("images");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((this.nameField != null)) {
                    if ((nameField.Equals(value) != true)) {
                        this.nameField = value;
                        this.OnPropertyChanged("name");
                    }
                }
                else {
                    this.nameField = value;
                    this.OnPropertyChanged("name");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((this.descriptionField != null)) {
                    if ((descriptionField.Equals(value) != true)) {
                        this.descriptionField = value;
                        this.OnPropertyChanged("description");
                    }
                }
                else {
                    this.descriptionField = value;
                    this.OnPropertyChanged("description");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string os {
            get {
                return this.osField;
            }
            set {
                if ((this.osField != null)) {
                    if ((osField.Equals(value) != true)) {
                        this.osField = value;
                        this.OnPropertyChanged("os");
                    }
                }
                else {
                    this.osField = value;
                    this.OnPropertyChanged("os");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string arch {
            get {
                return this.archField;
            }
            set {
                if ((this.archField != null)) {
                    if ((archField.Equals(value) != true)) {
                        this.archField = value;
                        this.OnPropertyChanged("arch");
                    }
                }
                else {
                    this.archField = value;
                    this.OnPropertyChanged("arch");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                if ((this.uriField != null)) {
                    if ((uriField.Equals(value) != true)) {
                        this.uriField = value;
                        this.OnPropertyChanged("uri");
                    }
                }
                else {
                    this.uriField = value;
                    this.OnPropertyChanged("uri");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                if ((this.versionField != null)) {
                    if ((versionField.Equals(value) != true)) {
                        this.versionField = value;
                        this.OnPropertyChanged("version");
                    }
                }
                else {
                    this.versionField = value;
                    this.OnPropertyChanged("version");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                if ((dateCreatedField.Equals(value) != true)) {
                    this.dateCreatedField = value;
                    this.OnPropertyChanged("dateCreated");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCreatedSpecified {
            get {
                return this.dateCreatedFieldSpecified;
            }
            set {
                if ((dateCreatedFieldSpecified.Equals(value) != true)) {
                    this.dateCreatedFieldSpecified = value;
                    this.OnPropertyChanged("dateCreatedSpecified");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                if ((dateModifiedField.Equals(value) != true)) {
                    this.dateModifiedField = value;
                    this.OnPropertyChanged("dateModified");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateModifiedSpecified {
            get {
                return this.dateModifiedFieldSpecified;
            }
            set {
                if ((dateModifiedFieldSpecified.Equals(value) != true)) {
                    this.dateModifiedFieldSpecified = value;
                    this.OnPropertyChanged("dateModifiedSpecified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public virtual void OnPropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null)) {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.16833")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="uri://matt.b/packet/")]
    public partial class imagesTypeImage : System.ComponentModel.INotifyPropertyChanged {
        
        private string srcField;
        
        private byte[] dataField;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=0)]
        public string src {
            get {
                return this.srcField;
            }
            set {
                if ((this.srcField != null)) {
                    if ((srcField.Equals(value) != true)) {
                        this.srcField = value;
                        this.OnPropertyChanged("src");
                    }
                }
                else {
                    this.srcField = value;
                    this.OnPropertyChanged("src");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField != null)) {
                    if ((dataField.Equals(value) != true)) {
                        this.dataField = value;
                        this.OnPropertyChanged("data");
                    }
                }
                else {
                    this.dataField = value;
                    this.OnPropertyChanged("data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public virtual void OnPropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null)) {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.16833")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="uri://matt.b/packet/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="uri://matt.b/packet/", IsNullable=false)]
    public partial class packets : System.ComponentModel.INotifyPropertyChanged {
        
        private ObservableCollection<packetsPacket> packetField;
        
        public packets() {
            this.packetField = new ObservableCollection<packetsPacket>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("packet", IsNullable=true, Order=0)]
        public ObservableCollection<packetsPacket> packet {
            get {
                return this.packetField;
            }
            set {
                if ((this.packetField != null)) {
                    if ((packetField.Equals(value) != true)) {
                        this.packetField = value;
                        this.OnPropertyChanged("packet");
                    }
                }
                else {
                    this.packetField = value;
                    this.OnPropertyChanged("packet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public virtual void OnPropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null)) {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.16833")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="uri://matt.b/packet/")]
    public partial class packetsPacket : System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] dataField;
        
        private ObservableCollection<imagesTypeImage> imagesField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string osField;
        
        private string archField;
        
        private string uriField;
        
        private string versionField;
        
        private System.DateTime dateCreatedField;
        
        private bool dateCreatedFieldSpecified;
        
        private System.DateTime dateModifiedField;
        
        private bool dateModifiedFieldSpecified;
        
        public packetsPacket() {
            this.imagesField = new ObservableCollection<imagesTypeImage>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField != null)) {
                    if ((dataField.Equals(value) != true)) {
                        this.dataField = value;
                        this.OnPropertyChanged("data");
                    }
                }
                else {
                    this.dataField = value;
                    this.OnPropertyChanged("data");
                }
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("image")]
        public ObservableCollection<imagesTypeImage> images {
            get {
                return this.imagesField;
            }
            set {
                if ((this.imagesField != null)) {
                    if ((imagesField.Equals(value) != true)) {
                        this.imagesField = value;
                        this.OnPropertyChanged("images");
                    }
                }
                else {
                    this.imagesField = value;
                    this.OnPropertyChanged("images");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((this.nameField != null)) {
                    if ((nameField.Equals(value) != true)) {
                        this.nameField = value;
                        this.OnPropertyChanged("name");
                    }
                }
                else {
                    this.nameField = value;
                    this.OnPropertyChanged("name");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((this.descriptionField != null)) {
                    if ((descriptionField.Equals(value) != true)) {
                        this.descriptionField = value;
                        this.OnPropertyChanged("description");
                    }
                }
                else {
                    this.descriptionField = value;
                    this.OnPropertyChanged("description");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string os {
            get {
                return this.osField;
            }
            set {
                if ((this.osField != null)) {
                    if ((osField.Equals(value) != true)) {
                        this.osField = value;
                        this.OnPropertyChanged("os");
                    }
                }
                else {
                    this.osField = value;
                    this.OnPropertyChanged("os");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string arch {
            get {
                return this.archField;
            }
            set {
                if ((this.archField != null)) {
                    if ((archField.Equals(value) != true)) {
                        this.archField = value;
                        this.OnPropertyChanged("arch");
                    }
                }
                else {
                    this.archField = value;
                    this.OnPropertyChanged("arch");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                if ((this.uriField != null)) {
                    if ((uriField.Equals(value) != true)) {
                        this.uriField = value;
                        this.OnPropertyChanged("uri");
                    }
                }
                else {
                    this.uriField = value;
                    this.OnPropertyChanged("uri");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                if ((this.versionField != null)) {
                    if ((versionField.Equals(value) != true)) {
                        this.versionField = value;
                        this.OnPropertyChanged("version");
                    }
                }
                else {
                    this.versionField = value;
                    this.OnPropertyChanged("version");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                if ((dateCreatedField.Equals(value) != true)) {
                    this.dateCreatedField = value;
                    this.OnPropertyChanged("dateCreated");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateCreatedSpecified {
            get {
                return this.dateCreatedFieldSpecified;
            }
            set {
                if ((dateCreatedFieldSpecified.Equals(value) != true)) {
                    this.dateCreatedFieldSpecified = value;
                    this.OnPropertyChanged("dateCreatedSpecified");
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateModified {
            get {
                return this.dateModifiedField;
            }
            set {
                if ((dateModifiedField.Equals(value) != true)) {
                    this.dateModifiedField = value;
                    this.OnPropertyChanged("dateModified");
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateModifiedSpecified {
            get {
                return this.dateModifiedFieldSpecified;
            }
            set {
                if ((dateModifiedFieldSpecified.Equals(value) != true)) {
                    this.dateModifiedFieldSpecified = value;
                    this.OnPropertyChanged("dateModifiedSpecified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public virtual void OnPropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null)) {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.16833")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri://matt.b/packet/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="uri://matt.b/packet/", IsNullable=true)]
    public partial class imagesType : System.ComponentModel.INotifyPropertyChanged {
        
        private ObservableCollection<imagesTypeImage> imageField;
        
        public imagesType() {
            this.imageField = new ObservableCollection<imagesTypeImage>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("image", IsNullable=true, Order=0)]
        public ObservableCollection<imagesTypeImage> image {
            get {
                return this.imageField;
            }
            set {
                if ((this.imageField != null)) {
                    if ((imageField.Equals(value) != true)) {
                        this.imageField = value;
                        this.OnPropertyChanged("image");
                    }
                }
                else {
                    this.imageField = value;
                    this.OnPropertyChanged("image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public virtual void OnPropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null)) {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
